on:
  push:
    tags:
      - '*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Build with dotnet
      run: dotnet build --configuration Release --nologo ./src/Lumina.sln
    - name: dotnet test
      run: dotnet test --configuration Release --nologo ./src/Lumina.sln
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Lumina-${{ matrix.os }}
        path: |
          ./src/Lumina/bin/Release/*.nupkg
          ./src/Lumina/bin/Release/*.snupkg
          ./src/Lumina/bin/Release/**/Lumina*.dll
          ./src/Lumina/bin/Release/**/Lumina*.xml
          ./src/Lumina/bin/Release/**/Lumina*.pdb
          ./src/Lumina/bin/Release/**/Lumina*.deps.json
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Lumina ${{ github.ref }}
        draft: false
        prerelease: false
